### ISSUE TITLE
[Question] favicon folder

### ISSUE THREAD

**Issue by gp-slick-coder** [davetimmins/random-destiny-grimoire#1]
Hi Dave, nice app and with especially fast startup time!

Your favicon folder is very interesting. There are a lot of files in it. Dit you do this all by hand or is there a tool available to generate this? Is there some good documentation on the web that describes all this specific device optimizations?

I also like to prepare my app as good as yours ;)

**Comment by davetimmins** [comment]
Thanks. I used http://realfavicongenerator.net/ as it seems to cover all the options. Looks like it's been updated since then too and has a simpler output now.

**Comment by gp-slick-coder** [comment]
Nice, thanks for the link!
